name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: 1.11.2

      - run: deno --version
      - run: deno fmt --check
      - run: deno test

      - name: Benchmarks
        run: deno run ./benchmarks/v1.ts
