name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.2

      - run: deno --version
      - run: deno fmt --check
      - run: deno test

      - name: Benchmarks
        run: deno run ./benchmarks/v1.ts

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'zhmushan/router'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
